# Generated by Django 4.2.3 on 2023-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
